name: Pre-commit Checks

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          
      - name: Run pre-commit
        run: pre-commit run --all-files
        
      # This step will show the exact files that were modified
      - name: Check for modified files
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "The following files were modified by pre-commit:"
            git status --porcelain
            exit 1
          fi